# Generated by Django 3.2.5 on 2021-08-16 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Рекорд')),
                ('count', models.IntegerField(default=0, verbose_name='Количество капчей')),
                ('all_time', models.FloatField(default=0, verbose_name='Всего времени')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
