# Generated by Django 3.2.5 on 2021-08-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210816_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='capKey',
            field=models.CharField(default='KeyN', max_length=15, verbose_name='Клавиша капчи'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delay',
            field=models.BooleanField(default=False, verbose_name='Задержка'),
        ),
    ]
