# Generated by Django 3.2.5 on 2021-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='Задержка'),
        ),
    ]
